### PR TITLE
Multifile upload

### PR DESCRIPTION
**Pull request by bitner**
This branch adds the ability to add multiple files at once. It will automatically unzip any first level zip files. It also allows uploading and configuring .sld styles and .xml metadata files. Examples of usage are included in the tests. 

There is no UI for adding the multiple files.

### CODE REVIEW

**Comment by jj0hns0n** [comment]
@garnertb can we look at this one together and get it merged?

**Comment by garnertb** [comment]
Thanks for the submission, below my feedback.  I'm really sorry for the delay in reviewing this.

- [ ] I’m not a fan of having divergent views, one to support single file uploads and one to support multiple file uploads. Could you refactor to implement a single view that supports both?
- [ ] Please include a migration for the new foreign key on the `UploadLayer`.
- [ ] There are no client-side changes, is this functionality not supported from the client-side workflow?
- [ ] The MultiUpload view should also be implemented as an API to support ajax based workflows.
- [ ]  The UploadFile model is duplicated in models.py.
- [ ] To make things a bit more DRY, I think the validation logic in Checkfile should be implemented on the UploadFileForm.
- [ ] Instead of up-merging into master, please rebase the code on top of master (which I did here for you: https://github.com/ProminentEdge/django-osgeo-importer/tree/multi)

**Comment by bitner** [comment]
Thanks for the review Tyler. Couple comments/questions.

The new view supports single or multiple file uploads. I did not get rid of the existing view as the new one necessarily changes the api and I did not want to cause a regression in the API. Should I remove the existing View/Form/Api code that is used for the single file upload?

Can you send me a pointer as to how to add the migration? I haven't use the migration mechanism with Django and could not find tools such as makemigration in the installed django.

As stated in the pull request, this pull did not address the GUI at all. Once we get this merged upstream we should create a new ticket. Possibly Sara can continue the work she just did for the UI to integrate.

The MultiUpload does (actually currently only) support use as an API with files + json submittal. It does not directly map to just a resource so it is not implemented with TastyPie.

I separated the CheckFile out in my head to be more DRY as I found myself using the logic in there in multiple places. Django Forms do not support arbitrary multiple file uploads which is why MultiUpload is implemented as a normal view and not a FormView at all.

Happy to hop on a call if easier to chat about any of these.

**Comment by garnertb** [comment]
> The new view supports single or multiple file uploads. I did not get rid of the existing view as the new one necessarily changes the api and I did not want to cause a regression in the API. Should I remove the existing View/Form/Api code that is used for the single file upload?

Not sure if it would be better to remove View/Form/API for the single upload or refactor it to include your multifile work so it supports multifile uploads.

> Can you send me a pointer as to how to add the migration? I haven't use the migration mechanism with Django and could not find tools such as makemigration in the installed django.

I think the default build gets an older version of Django just because we pegged it to an old version of GeoNode.  Bump up your Django version and `python manage.py makemigrations osgeo_importer` and you should be good.

> As stated in the pull request, this pull did not address the GUI at all. Once we get this merged upstream we should create a new ticket. Possibly Sara can continue the work she just did for the UI to integrate.

I prefer that GUI changes should be included before merging.

> The MultiUpload does (actually currently only) support use as an API with files + json submittal. It does not directly map to just a resource so it is not implemented with TastyPie.

Seems like it would still map to a `UploadedData` resource.  Which would have 1:N children files and layers.

> I separated the CheckFile out in my head to be more DRY as I found myself using the logic in there in multiple places. Django Forms do not support arbitrary multiple file uploads which is why MultiUpload is implemented as a normal view and not a FormView at all.

I think the validation logic in the MultiUpload view makes the view too complex.  The logic should be implemented on a lower level object (form or model) that can be reused more readily than a View.

Also happy discuss in a hangout if easier.

**Comment by jj0hns0n** [comment]
@garnertb @bitner where are we at on this guys?

**Comment by bitner** [comment]
All items have been addressed in a different branch reworking to deal with issues brought up. Closing this PR and will open a new PR from that branch.

**Pull request closed without merging**
