### PR TITLE
let tastypie version be flexible to avoid conflicts

### PR DESCRIPTION
**Pull request by sarasafavi**

### CODE REVIEW

**Comment by sarasafavi** [comment]
see also discussion at https://github.com/ProminentEdge/django-osgeo-importer/pull/19

This ignores the `numpy` dep that was rolled into that previous PR -- for now I'll have our consuming project handle via requirements.txt, but maybe in the future numpy can be added as a package dep as well

**Comment by garnertb** [comment]
@sarasafavi can you pin this to a specific version?

**Comment by sarasafavi** [comment]
@garnertb apologies; I misunderstand your suggestion in #19 

Note that this will drop support for Python 2.6, if you assumed any previously :)

**Comment by garnertb** [comment]
Why will this drop 2.6 support?  Tastypie 0.12.2 seems to support it: https://pypi.python.org/pypi/django-tastypie/0.12.2.

**Comment by sarasafavi** [comment]
I based my comment on this: https://django-tastypie.readthedocs.io/en/latest/release_notes/v0.12.2.html

(Title is wrong, URL is correct, those are release notes for 0.12.2)

**Comment by sarasafavi** [comment]
Reopened from Boundless's fork at https://github.com/ProminentEdge/django-osgeo-importer/pull/28

**Pull request closed without merging**
